// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zoo.Infrastructure;

#nullable disable

namespace Zoo.Infrastructure.Migrations
{
    [DbContext(typeof(ZooContext))]
    [Migration("20250529165717_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Zoo.Infrastructure.Data.AnimalModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ZookeeperId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ZookeeperId");

                    b.ToTable("AnimalModel");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Zoo.Infrastructure.Data.ZookeeperModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Zookeepers");
                });

            modelBuilder.Entity("Zoo.Infrastructure.Data.LionModel", b =>
                {
                    b.HasBaseType("Zoo.Infrastructure.Data.AnimalModel");

                    b.Property<bool>("IsAlpha")
                        .HasColumnType("bit");

                    b.ToTable("Lions", (string)null);
                });

            modelBuilder.Entity("Zoo.Infrastructure.Data.ParrotModel", b =>
                {
                    b.HasBaseType("Zoo.Infrastructure.Data.AnimalModel");

                    b.Property<string>("Phrase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Parrots", (string)null);
                });

            modelBuilder.Entity("Zoo.Infrastructure.Data.AnimalModel", b =>
                {
                    b.HasOne("Zoo.Infrastructure.Data.ZookeeperModel", "Zookeeper")
                        .WithMany("Animals")
                        .HasForeignKey("ZookeeperId");

                    b.Navigation("Zookeeper");
                });

            modelBuilder.Entity("Zoo.Infrastructure.Data.LionModel", b =>
                {
                    b.HasOne("Zoo.Infrastructure.Data.AnimalModel", null)
                        .WithOne()
                        .HasForeignKey("Zoo.Infrastructure.Data.LionModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zoo.Infrastructure.Data.ParrotModel", b =>
                {
                    b.HasOne("Zoo.Infrastructure.Data.AnimalModel", null)
                        .WithOne()
                        .HasForeignKey("Zoo.Infrastructure.Data.ParrotModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zoo.Infrastructure.Data.ZookeeperModel", b =>
                {
                    b.Navigation("Animals");
                });
#pragma warning restore 612, 618
        }
    }
}
